### ISSUE TITLE
Advanced flow missing

### ISSUE THREAD

**Issue by koenvervloesem** [mrpjevans/fortniteticker#1]
Hi PJ, I just read your article in The MagPi 78 and at the end of the Fortnite article you talk about an 'advanced' flow we can download here. However, I only see an advanced Python script in this repository, not an advanced Node-RED flow. Is this file missing?

**Comment by mrpjevans** [comment]
Hi, It's actually the Python script included in the repo. I decided to go with Python rather than Node RED so I could demonstrate how to use the API in different languages.

**Comment by koenvervloesem** [comment]
Ok, thanks for the clarification!
